config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'users/sessions' }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'pages#home'

  resources :appartments do
    resources :bookings, only: [:create, :destroy]
  end

  resources :bookings, only: [:index]

  get 'user_appartments', to: 'appartments#user_appartments'
end

app/models/appartment.rb
class Appartment < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_one_attached :photo
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  def available?(appartment, start_date, end_date)
    appartment.bookings.each do |b|
      return false if (b.start_date..b.end_date).overlaps?(start_date.to_date..end_date.to_date)
    end
    true
  end
end

app/controllers/appartments_controller.rb
class AppartmentsController < ApplicationController
  skip_before_action :authenticate_user!, only: :index
  before_action :set_appartment, only: [:show, :edit, :update, :destroy]

  def index
    # if params[:search][:address].empty?
    #   @appartments = Appartment.near(Geocoder.search(remote_ip).first.city, 250, :order => :distance)
    # end
    # if params[:search][:start_date].present? && params[:search][:end_date].present?
    nearest_appartments = Appartment.near(params[:search][:address], 250, :order => :distance)
    @appartments = nearest_appartments.select { |appartment| appartment.available?(appartment, params[:search][:start_date], params[:search][:end_date]) }
    # end
  end

  def user_appartments
    if current_user.appartments.empty?
      render 'new'
    else
      @appartments = current_user.appartments
    end
  end

  def show
    @booking = Booking.new
    @bookings = Booking.where(appartment_id: @appartment.id)
    @bookings_dates = @bookings.map do |booking|
      {
        from: booking.start_date,
        to:   booking.end_date
      }
    end
  end

  def new
    @appartment = Appartment.new
  end

  def create
    @appartment = Appartment.new(appartment_params)
    @appartment.user_id = current_user.id
    @appartment.save

    redirect_to appartment_path(@appartment)
  end

  def update
  end

  def destroy
  end

  private

  def set_appartment
    @appartment = Appartment.find(params[:id])
  end

  def appartment_params
    params.require(:appartment).permit(:address, :price, :photo)
  end

  # def nearest_appartments
  #   if params[:search][:address].empty?
  #     @appartments = Appartment.near(Geocoder.search(remote_ip).first.city, 250, order: :distance)
  #   end
  #   @appartments = Appartment.near(params[:address], 250, :order => :distance)
  # end
end

app/helpers/appartments_helper.rb
module AppartmentsHelper
end

app/views/appartments/index.html.erb
<div class="flex">
  <div id="appartments" class="w-8/12 content p-4 overflow-y-auto">
    <div class="p-4">
      <span class="text-sm"> 300+ stays ·  Feb 23 - 25</span>
      <h1 class="font-title font-bold text-3xl">Stays in the area selected</h1>
    </div>
    <% @appartments.each do |appartment| %>
      <%= link_to appartment_path(appartment) do %>
        <div class="relative w-full flex h-82 flex-row border-b border-gray-300 p-4">
          <%= cl_image_tag appartment.photo.key, class: "rounded-lg h-56"%>
          <div class="p-4">
            <span> <%= appartment.address %></span>
            <h3 class="font-body text-xl font-light"><%= appartment.title %></h3>
            <button class="absolute top-4 right-4">
              <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-heart"><path d="M20.84 4.61a5.5 5.5 0 0 0-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 0 0-7.78 7.78l1.06 1.06L12 21.23l7.78-7.78 1.06-1.06a5.5 5.5 0 0 0 0-7.78z"></path></svg>
            </button>
            <div class="absolute bottom-4 right-4">
              <p><span class="font-bold text-2xl"><%= appartment.price %>€</span> / nuit</p>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="w-4/12">
    <%= image_tag('map', class: "content object-cover") %>
  </div>
</div>

app/views/appartments/new.html.erb
<div class="grid grid-flow-col grid-cols-1 md:grid-cols-2 h-screen">
  <div class="relative flex flex-col justify-start items-center pt-32 px-12 pb-12 ">
    <h1 class="font-bold font-title text-5xl">Let's get started <%= current_user.first_name %>...</h1>
    <%= simple_form_for(@appartment, :html=> { class: 'w-full mt-16 h-56 justify-self-end' } ) do |f| %>
      <div class="form-inputs">
        <%= f.input :address,
                    :label => "Where do you live?",
                    required: false,
                    autofocus: true,
                    placeholder: '33 rue de Madrid, Paris, 75008, France',
                    input_html: { id: 'aloglia_search_address', autocomplete: "off", class: "mt-2 focus:ring-gray-800 focus:border-gray-800 block w-full pr-12 py-6 sm:text-sm border-gray-300 rounded-md mb-2" },
                    label_html: { class: "text-sm font-bold" } %>
        <%= f.input :price,
                    :label => "How much would like to earn per night?",
                    required: false,
                    autofocus: true,
                    placeholder: '50€',
                    wrapper_html: { class: "mt-6" },
                    input_html: { autocomplete: "off", class: "mt-2 focus:ring-gray-800 focus:border-gray-800 block w-full pr-4 py-4 sm:text-sm border-gray-300 rounded-md mb-2" },
                    label_html: { class: "text-sm font-bold" } %>
      </div>
      <div class="form-actions mt-8">
        <%= f.button :submit, "Continue", class: "w-full cursor-pointer inline-flex justify-center rounded-md border border-transparent shadow-sm px-4 py-4 mb-2 bg-rose-600 text-base font-medium text-white hover:bg-rose-500 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-red-500 sm:text-sm" %>
      </div>
    <% end %>
    <%= link_to :back, class: "absolute flex items-center justify-center bottom-12 left-12 p-2 rounded-full bg-rose-600 hover:bg-rose-500 w-auto cursor-pointer" do %>
      <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="white" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-chevron-left"><polyline points="15 18 9 12 15 6"></polyline></svg>
    <% end %>
  </div>
  <div class="hidden md:block">
    <img class="w-full object-cover h-screen" src="https://images.unsplash.com/photo-1583847268964-b28dc8f51f92?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=668&q=80" alt="">
  </div>
</div>

app/views/appartments/show.html.erb
<div class="max-w-7xl mx-auto">
  <div class="header">
    <h1 class="font-bold text-5xl font-title mt-12"><%= @appartment.title %></h1>
    <%= cl_image_tag @appartment.photo.key, class: "w-full h-96 object-cover rounded-lg mt-12"%>
  </div>
  <div id="body" class="flex flex-row pt-12">
    <div class="w-2/3">
      <div class="Introduction">
        <h2 class="font-title text-3xl">Chambre dans boutique-hôtel. Hôte : <%= @appartment.user.first_name %></h2>
        <p>2 voyageurs · 1 chambre · 1 salle de bain</p>
      </div>
      <div class="description">
        <div class="mt-8 pr-24">
          <%= @appartment.description %>
        </div>
      </div>
    </div>
    <div id="booking" class="">
      <div class="shadow border border-gray-300 rounded">
        <%= simple_form_for [@appartment, @booking] do |f| %>
          <%= f.input  :start_date, as: :string, required: false, input_html: {id: "range_start", class: "hidden"}, label_html: { class: "hidden" } %>
          <%= f.input  :end_date, as: :string, label: false, required: false, input_html: {id: "range_end", class: "hidden" } %>
            <div id="booking-form-div" data-bookings="<%= @bookings_dates.to_json %>">
              <div class="">
                <%= f.button :submit, "Reserve", class: "text-white font-medium font-title py-6 px-4 bg-rose-500 w-full cursor-pointer" %>
              </div>
            </div>
        <% end %>
      </div>
    </div>
  </div>
  <div id="map" class="rounded border border-gray-200 shadow w-full">

  </div>
</div>

app/views/appartments/user_appartments.html.erb
<h1 class="text-3xl font-bold font-title p-4">Your appartments:</h1>
<div class="grid grid-cols-3 gap-4 p-4">
  <% @appartments.each_with_index do |appartment, index| %>
    <%= link_to appartment_path(appartment) do %>
      <div class="shadow rounded-md overflow-hidden">
        <div class="card-header">
          <%= cl_image_tag appartment.photo.key, class: "w-full h-96 object-cover rounded-t-lg"%>
        </div>
        <div class="card-body p-4">
          <h2>Logement n°<%= index + 1 %> </h2>
          <p> <%= appartment.address %></p>
        </div>
      </div>
    <% end %>
  <% end %>
  <%= link_to new_appartment_path do %>
  <div style="height: 464px;"class="flex justify-center items-center shadow rounded-md overflow-hidden bg-gradient-to-r from-rose-400 to-rose-500">
    <h2 class="text-5xl text-center text-white font-title font-bold">Add a new Appartment</h2>
  </div>
  <% end %>
</div>